version: "3.7"

services:
  web:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: json-file
      options:
        mode: non-blocking
        max-buffer-size: 4m
