# fly.toml app configuration file generated for podcastdataendpoint-wandering-haze-827 on 2023-12-01T16:13:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "podcastdataendpoint"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
